package com.myspace.usermanagementworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdminChecker implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "userData")
	private com.myspace.usermanagementworkflow.UserData userData;
	@org.kie.api.definition.type.Label(value = "approve")
	private java.lang.Boolean approve;

	public AdminChecker() {
	}

	public com.myspace.usermanagementworkflow.UserData getUserData() {
		return this.userData;
	}

	public void setUserData(com.myspace.usermanagementworkflow.UserData userData) {
		this.userData = userData;
	}

	public java.lang.Boolean getApprove() {
		return this.approve;
	}

	public void setApprove(java.lang.Boolean approve) {
		this.approve = approve;
	}

	public AdminChecker(com.myspace.usermanagementworkflow.UserData userData,
			java.lang.Boolean approve) {
		this.userData = userData;
		this.approve = approve;
	}

}