package com.myspace.usermanagementworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "username")
	private java.lang.String username;
	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "firstname")
	private java.lang.String firstname;
	@org.kie.api.definition.type.Label(value = "lastname")
	private java.lang.String lastname;
	@org.kie.api.definition.type.Label(value = "roles")
	private java.lang.String roles;

	public UserData() {
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(java.lang.String firstname) {
		this.firstname = firstname;
	}

	public java.lang.String getLastname() {
		return this.lastname;
	}

	public void setLastname(java.lang.String lastname) {
		this.lastname = lastname;
	}

	public java.lang.String getRoles() {
		return this.roles;
	}

	public void setRoles(java.lang.String roles) {
		this.roles = roles;
	}

	public UserData(java.lang.String username, java.lang.String email,
			java.lang.String firstname, java.lang.String lastname,
			java.lang.String roles) {
		this.username = username;
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.roles = roles;
	}

}